title = "FFmpeg By Example"
baseURL = "/"
enableRobotsTXT = true

[params]
  apiURL = "https://ffmpegbyexample.com"
  favicon = "/favicon.ico"
  description = "Explore the depth of FFmpeg with Examples"
  examplestypes = ["no-preview", "picture", "video-url", "youtube-embed", "audio"]

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      Cross-Origin-Embedder-Policy = "require-corp"
      Cross-Origin-Opener-Policy = "same-origin" 
      Cross-Origin-Resource-Policy = "cross-origin"
      Cross-Origin-Worker-Policy = "same-origin"

      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, OPTIONS"
      Access-Control-Allow-Headers = "*"

      Content-Security-Policy = "frame-ancestors 'self' https://ffmpeg.wide.video https://ko-fi.com"

[permalinks]
  posts = "/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML"]

[examples]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
