title = "FFmpeg By Example"
enableRobotsTXT = true

googleAnalytics = "G-NVHSTNVELB"

[params]
  #Favicon for site
  favicon = "/favicon.ico"

[permalinks]
  posts = "/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML"]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
