title = "FFmpeg By Example"
enableRobotsTXT = true

[params]
  favicon = "/favicon.ico"
  description = "Explore the depth of FFmpeg with Examples"
  examplestypes = ["no-preview", "picture", "video-url", "youtube-embed", "audio"]
[permalinks]
  posts = "/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML"]

[examples]

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
